import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { cookies } from "next/headers";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("access_token");
  async function handleLogout() {
    "use server";
    const cookieStore = await cookies();
    cookieStore.delete("access_token");
  }
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {token?.value && (
          <div className="flex justify-between px-4 py-3">
            <div className="flex gap-2 items-center">
              <Link href={"/"}>Home</Link>
              <Link href={"/products"}>Product</Link>
              <Link href={"/wishlist"}>Wishlist</Link>
            </div>
            <div>
              <img src="/vans-navbar-logo.png" alt="" />
            </div>
            <form action={handleLogout} className="flex items-center">
              <button type="submit" className="cursor-pointer">
                Logout
              </button>
            </form>
          </div>
        )}
        {!token?.value && (
          <div className="flex justify-between px-4 py-3">
            <div className="flex gap-2 items-center">
              <Link href={"/"}>Home</Link>
              <Link href={"/products"}>Product</Link>
              <Link href={"/wishlist"}>Wishlist</Link>
            </div>
            <div>
              <img src="/vans-navbar-logo.png" alt="" />
            </div>

            <div className="flex gap-2 items-center">
              <Link href={"/login"}>Login</Link>
              <Link href={"/register"}>Register</Link>
            </div>
          </div>
        )}

        {children}
      </body>
    </html>
  );
}
